// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr6iB24WtIDwAH8VE1muEoVOnt8HkRJJk',
    appId: '1:654717080679:web:7c768f0c08deaf620bf0c2',
    messagingSenderId: '654717080679',
    projectId: 'emmie-base',
    authDomain: 'emmie-base.firebaseapp.com',
    storageBucket: 'emmie-base.appspot.com',
    measurementId: 'G-J1L03F3C20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCkbzjm_MVdHZPq-rFXKfEsmvbd0jbMQY',
    appId: '1:654717080679:android:a4374d29c26fce400bf0c2',
    messagingSenderId: '654717080679',
    projectId: 'emmie-base',
    storageBucket: 'emmie-base.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGikUV0XorVCtxmtCZWTKys1iXwswWLLw',
    appId: '1:654717080679:ios:098245c0e17e822f0bf0c2',
    messagingSenderId: '654717080679',
    projectId: 'emmie-base',
    storageBucket: 'emmie-base.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGikUV0XorVCtxmtCZWTKys1iXwswWLLw',
    appId: '1:654717080679:ios:4680d1993a6bc3af0bf0c2',
    messagingSenderId: '654717080679',
    projectId: 'emmie-base',
    storageBucket: 'emmie-base.appspot.com',
    iosBundleId: 'com.example.tiktokClone.RunnerTests',
  );
}
